server:
  port: 8080
  servlet:
    context-path: /docker-connection-between-containers

spring:
  datasource:
    initialization-mode: always
    data: classpath:data.sql
    url: jdbc:mysql://localhost:3306/customers
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
