version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: customers
      MYSQL_ROOT_PASSWORD: password

  customer-app:
    image: customer-app:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.122.1:3306/customers